#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="project")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMember_add(Member_add instance);
    partial void UpdateMember_add(Member_add instance);
    partial void DeleteMember_add(Member_add instance);
    partial void Insertbookadd1(bookadd1 instance);
    partial void Updatebookadd1(bookadd1 instance);
    partial void Deletebookadd1(bookadd1 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Project.Properties.Settings.Default.projectConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Loggin> Loggins
		{
			get
			{
				return this.GetTable<Loggin>();
			}
		}
		
		public System.Data.Linq.Table<bookadd> bookadds
		{
			get
			{
				return this.GetTable<bookadd>();
			}
		}
		
		public System.Data.Linq.Table<Member_add> Member_adds
		{
			get
			{
				return this.GetTable<Member_add>();
			}
		}
		
		public System.Data.Linq.Table<bookadd1> bookadd1s
		{
			get
			{
				return this.GetTable<bookadd1>();
			}
		}
		
		public System.Data.Linq.Table<issubook> issubooks
		{
			get
			{
				return this.GetTable<issubook>();
			}
		}
		
		public System.Data.Linq.Table<tbl_category> tbl_categories
		{
			get
			{
				return this.GetTable<tbl_category>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad")]
		public int ad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="F_Name", DbType="VarChar(50)")] string f_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cnic", DbType="VarChar(50)")] string cnic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="VarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adress", DbType="VarChar(50)")] string adress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(50)")] string gender)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, f_Name, cnic, phone, adress, gender);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_member")]
		public ISingleResult<select_memberResult> select_member()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_memberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ad_member")]
		public int ad_member([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="F_Name", DbType="VarChar(50)")] string f_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cnic", DbType="VarChar(50)")] string cnic, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="VarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adress", DbType="VarChar(50)")] string adress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(50)")] string gender)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, f_Name, cnic, phone, adress, gender);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.bokad")]
		public int bokad([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Book_Name", DbType="VarChar(50)")] string book_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IBSN", DbType="VarChar(50)")] string iBSN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(50)")] string title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Auther", DbType="VarChar(50)")] string auther)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), book_Name, category, iBSN, title, auther);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.bookshow")]
		public ISingleResult<bookshowResult> bookshow()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<bookshowResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isubook")]
		public int isubook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Book_Name", DbType="VarChar(50)")] string book_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Member_Name", DbType="VarChar(50)")] string member_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Issuedate", DbType="Date")] System.Nullable<System.DateTime> issuedate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ruturn_Date", DbType="Date")] System.Nullable<System.DateTime> ruturn_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Return_Days", DbType="Int")] System.Nullable<int> return_Days)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), book_Name, member_Name, issuedate, ruturn_Date, return_Days);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.isubookdetail")]
		public ISingleResult<isubookdetailResult> isubookdetail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<isubookdetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteBok")]
		public int deleteBok([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loggin")]
	public partial class Loggin
	{
		
		private string _Name;
		
		private string _pasword;
		
		public Loggin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasword", DbType="VarChar(50)")]
		public string pasword
		{
			get
			{
				return this._pasword;
			}
			set
			{
				if ((this._pasword != value))
				{
					this._pasword = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bookadd")]
	public partial class bookadd
	{
		
		private string _Book_Name;
		
		private string _ISBN;
		
		private string _Title;
		
		private string _Auther;
		
		public bookadd()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Name", DbType="VarChar(50)")]
		public string Book_Name
		{
			get
			{
				return this._Book_Name;
			}
			set
			{
				if ((this._Book_Name != value))
				{
					this._Book_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="VarChar(50)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auther", DbType="VarChar(50)")]
		public string Auther
		{
			get
			{
				return this._Auther;
			}
			set
			{
				if ((this._Auther != value))
				{
					this._Auther = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Member_add")]
	public partial class Member_add : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Member_Id;
		
		private string _Name;
		
		private string _F_Name;
		
		private string _Cnic;
		
		private string _Phone;
		
		private string _Adress;
		
		private string _Gender;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMember_IdChanging(int value);
    partial void OnMember_IdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnF_NameChanging(string value);
    partial void OnF_NameChanged();
    partial void OnCnicChanging(string value);
    partial void OnCnicChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    #endregion
		
		public Member_add()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Member_Id
		{
			get
			{
				return this._Member_Id;
			}
			set
			{
				if ((this._Member_Id != value))
				{
					this.OnMember_IdChanging(value);
					this.SendPropertyChanging();
					this._Member_Id = value;
					this.SendPropertyChanged("Member_Id");
					this.OnMember_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Name", DbType="VarChar(50)")]
		public string F_Name
		{
			get
			{
				return this._F_Name;
			}
			set
			{
				if ((this._F_Name != value))
				{
					this.OnF_NameChanging(value);
					this.SendPropertyChanging();
					this._F_Name = value;
					this.SendPropertyChanged("F_Name");
					this.OnF_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cnic", DbType="VarChar(50)")]
		public string Cnic
		{
			get
			{
				return this._Cnic;
			}
			set
			{
				if ((this._Cnic != value))
				{
					this.OnCnicChanging(value);
					this.SendPropertyChanging();
					this._Cnic = value;
					this.SendPropertyChanged("Cnic");
					this.OnCnicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="VarChar(50)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bookadd")]
	public partial class bookadd1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _List;
		
		private string _Book_Name;
		
		private string _category;
		
		private string _ISBN;
		
		private string _Title;
		
		private string _Auther;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnListChanging(int value);
    partial void OnListChanged();
    partial void OnBook_NameChanging(string value);
    partial void OnBook_NameChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAutherChanging(string value);
    partial void OnAutherChanged();
    #endregion
		
		public bookadd1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_List", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int List
		{
			get
			{
				return this._List;
			}
			set
			{
				if ((this._List != value))
				{
					this.OnListChanging(value);
					this.SendPropertyChanging();
					this._List = value;
					this.SendPropertyChanged("List");
					this.OnListChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Name", DbType="VarChar(50)")]
		public string Book_Name
		{
			get
			{
				return this._Book_Name;
			}
			set
			{
				if ((this._Book_Name != value))
				{
					this.OnBook_NameChanging(value);
					this.SendPropertyChanging();
					this._Book_Name = value;
					this.SendPropertyChanged("Book_Name");
					this.OnBook_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="VarChar(50)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auther", DbType="VarChar(50)")]
		public string Auther
		{
			get
			{
				return this._Auther;
			}
			set
			{
				if ((this._Auther != value))
				{
					this.OnAutherChanging(value);
					this.SendPropertyChanging();
					this._Auther = value;
					this.SendPropertyChanged("Auther");
					this.OnAutherChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.issubook")]
	public partial class issubook
	{
		
		private string _Book_Name;
		
		private string _Member_Name;
		
		private System.Nullable<System.DateTime> _Issuedate;
		
		private System.Nullable<System.DateTime> _Ruturn_Date;
		
		private System.Nullable<int> _Return_Days;
		
		public issubook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Name", DbType="VarChar(50)")]
		public string Book_Name
		{
			get
			{
				return this._Book_Name;
			}
			set
			{
				if ((this._Book_Name != value))
				{
					this._Book_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Name", DbType="VarChar(50)")]
		public string Member_Name
		{
			get
			{
				return this._Member_Name;
			}
			set
			{
				if ((this._Member_Name != value))
				{
					this._Member_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issuedate", DbType="Date")]
		public System.Nullable<System.DateTime> Issuedate
		{
			get
			{
				return this._Issuedate;
			}
			set
			{
				if ((this._Issuedate != value))
				{
					this._Issuedate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruturn_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Ruturn_Date
		{
			get
			{
				return this._Ruturn_Date;
			}
			set
			{
				if ((this._Ruturn_Date != value))
				{
					this._Ruturn_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Days", DbType="Int")]
		public System.Nullable<int> Return_Days
		{
			get
			{
				return this._Return_Days;
			}
			set
			{
				if ((this._Return_Days != value))
				{
					this._Return_Days = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_category")]
	public partial class tbl_category
	{
		
		private int _cat_id;
		
		private string _cat_name;
		
		public tbl_category()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int NOT NULL")]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this._cat_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_name
		{
			get
			{
				return this._cat_name;
			}
			set
			{
				if ((this._cat_name != value))
				{
					this._cat_name = value;
				}
			}
		}
	}
	
	public partial class select_memberResult
	{
		
		private int _Member_Id;
		
		private string _Name;
		
		private string _F_Name;
		
		private string _Cnic;
		
		private string _Phone;
		
		private string _Adress;
		
		private string _Gender;
		
		public select_memberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Id", DbType="Int NOT NULL")]
		public int Member_Id
		{
			get
			{
				return this._Member_Id;
			}
			set
			{
				if ((this._Member_Id != value))
				{
					this._Member_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F_Name", DbType="VarChar(50)")]
		public string F_Name
		{
			get
			{
				return this._F_Name;
			}
			set
			{
				if ((this._F_Name != value))
				{
					this._F_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cnic", DbType="VarChar(50)")]
		public string Cnic
		{
			get
			{
				return this._Cnic;
			}
			set
			{
				if ((this._Cnic != value))
				{
					this._Cnic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="VarChar(50)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this._Adress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
	}
	
	public partial class bookshowResult
	{
		
		private int _List;
		
		private string _Book_Name;
		
		private string _category;
		
		private string _ISBN;
		
		private string _Title;
		
		private string _Auther;
		
		public bookshowResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_List", DbType="Int NOT NULL")]
		public int List
		{
			get
			{
				return this._List;
			}
			set
			{
				if ((this._List != value))
				{
					this._List = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Name", DbType="VarChar(50)")]
		public string Book_Name
		{
			get
			{
				return this._Book_Name;
			}
			set
			{
				if ((this._Book_Name != value))
				{
					this._Book_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="VarChar(50)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Auther", DbType="VarChar(50)")]
		public string Auther
		{
			get
			{
				return this._Auther;
			}
			set
			{
				if ((this._Auther != value))
				{
					this._Auther = value;
				}
			}
		}
	}
	
	public partial class isubookdetailResult
	{
		
		private string _Book_Name;
		
		private string _Member_Name;
		
		private System.Nullable<System.DateTime> _Issuedate;
		
		private System.Nullable<System.DateTime> _Ruturn_Date;
		
		private System.Nullable<int> _Return_Days;
		
		public isubookdetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Name", DbType="VarChar(50)")]
		public string Book_Name
		{
			get
			{
				return this._Book_Name;
			}
			set
			{
				if ((this._Book_Name != value))
				{
					this._Book_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Name", DbType="VarChar(50)")]
		public string Member_Name
		{
			get
			{
				return this._Member_Name;
			}
			set
			{
				if ((this._Member_Name != value))
				{
					this._Member_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issuedate", DbType="Date")]
		public System.Nullable<System.DateTime> Issuedate
		{
			get
			{
				return this._Issuedate;
			}
			set
			{
				if ((this._Issuedate != value))
				{
					this._Issuedate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruturn_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Ruturn_Date
		{
			get
			{
				return this._Ruturn_Date;
			}
			set
			{
				if ((this._Ruturn_Date != value))
				{
					this._Ruturn_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Days", DbType="Int")]
		public System.Nullable<int> Return_Days
		{
			get
			{
				return this._Return_Days;
			}
			set
			{
				if ((this._Return_Days != value))
				{
					this._Return_Days = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
